### PR TITLE
Add more plants

### PR DESCRIPTION
**Pull request by no-lex**
In this PR
Parviflora 448 poly
Cannibis 840 poly
Fern 3 608 poly
Weed 11 poly
Shrub 472 poly
Large shrub 1443 poly
Red shrubs 508&704 poly

For reference, the existing mapmodel nobiax/gaz_tank has 812 polys.

Preview:

### CODE REVIEW

**Comment by TheAssassin** [comment]
Those plants look pretty. But the number of polys of "large shrub" is a bit high. Did you test the impact on performance?

**Comment by no-lex** [comment]
70 fps on intel hd 3000/ i5 2520m with 50 mapmodels

**Comment by TheAssassin** [comment]
Cannot really say if that's good or bad. I guess that's okayish.

**Comment by lsalzman** [comment]
"Performs okay here" is not significant justification as to good performance, sorry, especially when there's nothing else in the map. If anyone were to actually spam these models in large numbers they'd basically tank performance, especially without any form of LOD on them.

I doubt anyone is going to look at these and just use one or two. The default inclination of most well-intentioned mappers is going to be to just spam these all over a map.

**Comment by no-lex** [comment]
Giving mapmakers the tools to make a pretty map should not be withheld because they have the possibility of causing lag when used improperly. It would not be a bad idea to provide the number of polygons each model has, however; should I rename the mapmodels to indicate polygon count?

**Comment by qreeves** [comment]
I'd just remove the ones with high counts. It's not about withholding them but knowing that they wouldn't be good in terms of performance (in terms of big picture, not limited use) - this is a consideration for any program, not just a game/engine. As I said before you made this PR, they need to have good optimisation as a lot of nobiax models use way too many vertices.

**Comment by no-lex** [comment]
Ok, removed a couple: the somewhat redundant higher-poly red shrub, and the big 1440 poly shrub.

**Pull request merged**
